### ISSUE TITLE
VS2019

### ISSUE THREAD

**Issue by lobbin** [ibauersachs/OpenCymd.Nps#1]
Trying to get this running on a Windows Server 2016, compiled with VS2019.

The only obvious I get is an error in NPS event log.
"The request was discarded because an extension dll crashed or malfunctioned."

I tried attaching to the services process for debug, but probably not sure I'm doing it right, as breakpoints or debug output doesn't work either.

**Comment by ibauersachs** [comment]
Assuming you did everything mentioned in the readme, I can't really help you out since I haven't used this in more than 7 years.
I don't know if NPS runs in it's own process nowadays. Back when I developed this, I needed to move the NPS service from the netsvcs group into a dedicated group (svchost.exe's -k parameter) for proper debugging.

**Comment by lobbin** [comment]
Thank you for leading me in the right direction, it actually was a permission error after all. I found that the managed dll ran in a dllhost process running as "network service". Once done, I managed to get my module running as expected.
